### ISSUE TITLE
星尘历史记录多的情况下的查询速度

### ISSUE THREAD

**Issue by DragonFlyEast** [NewLifeX/Stardust#65]
Net8.0 + Mysql 5.7 机器 8核 32G

代码版本为今天克隆的master编译，

星尘日志如下

```
22:13:56.723 49 Y TP 慢SQL[2,995ms] [StardustData] Select Count(*) From NodeHistory Where NodeID=5
22:13:56.723 48 Y TP 慢SQL[17,704ms] [StardustData] Select Count(*) From NodeHistory Where NodeID=5
22:14:40.702 48 Y TP 慢SQL[24,502ms] [StardustData] Select Count(*) From NodeHistory
22:15:11.237 48 Y TP 慢SQL[30,533ms] [StardustData] Select * From NodeHistory Where NodeID=5 Order By Id Desc limit 1082380, 20
22:15:11.268 48 Y TP [http://192.168.1.3/Nodes/NodeHistory?nodeId=5&PageIndex=54120]的错误 0HN5QR3AGOCD6:00000002
22:15:11.273 48 Y TP XCode.Exceptions.XSqlException: Fatal error encountered during command execution.[SQL:[StardustData] Select * From NodeHistory Where NodeID=5 Order By Id Desc limit 1082380, 20]
   at XCode.DataAccessLayer.DbSession.<>c__DisplayClass34_0`1.<Execute>b__1(DbConnection conn)
   at XCode.DataAccessLayer.DbSession.Process[TResult](Func`2 callback)
   at XCode.DataAccessLayer.DbSession.Execute[T](DbCommand cmd, Boolean query, Func`2 callback)
   at XCode.DataAccessLayer.DbSession.Query(String sql, IDataParameter[] ps)
   at XCode.DataAccessLayer.DAL.Invoke[T1,T2,T3,TResult](IDbSession session, T1 k1, T2 k2, T3 k3, Func`5 callback, String action)
   at XCode.DataAccessLayer.DAL.QueryWrap[T1,T2,T3,TResult](T1 k1, T2 k2, T3 k3, Func`5 callback, String action)
   at XCode.DataAccessLayer.DAL.Query(SelectBuilder builder, Int64 startRowIndex, Int64 maximumRows)
   at XCode.Entity`1.FindAll(Expression where, String order, String selects, Int64 startRowIndex, Int64 maximumRows)
   at XCode.Entity`1.FindAll(Expression where, PageParameter page, String selects)
   at Stardust.Data.Nodes.NodeHistory.Search(Int32 nodeId, Int32 provinceId, Int32 cityId, String action, Nullable`1 success, DateTime start, DateTime end, String key, PageParameter page) in D:\Stardust-0812\Stardust.Data\Nodes\节点历史.Biz.cs:line 127
   at Stardust.Web.Areas.Nodes.Controllers.NodeHistoryController.Search(Pager p) in D:\Stardust-0812\Stardust.Web\Areas\Nodes\Controllers\NodeHistoryController.cs:line 75
   at NewLife.Cube.ReadOnlyEntityController`1.SearchData(Pager p)
   at NewLife.Cube.ReadOnlyEntityController`1.IndexView(Pager p)
   at NewLife.Cube.ReadOnlyEntityController`1.Index(Pager p)
   at lambda_method472(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at NewLife.Cube.WebMiddleware.TenantMiddleware.Invoke(HttpContext ctx)
   at NewLife.Cube.WebMiddleware.RunTimeMiddleware.Invoke(HttpContext ctx)
```

```
23:07:58.450 38 Y TP 慢SQL[16,618ms] [StardustData] Select Count(*) From NodeData Where NodeID=1
23:10:37.647 37 Y TP 慢SQL[30,500ms] [StardustData] Select * From NodeData Where NodeID=1 Order By Id Desc limit 488160, 1440
23:10:37.650 37 Y TP [http://192.168.1.3/Nodes/NodeData?nodeId=1&PageIndex=340&PageSize=1440]的错误 0HN5QR3AGOCF5:00000002
23:10:37.654 37 Y TP XCode.Exceptions.XSqlException: Fatal error encountered during command execution.[SQL:[StardustData] Select * From NodeData Where NodeID=1 Order By Id Desc limit 488160, 1440]
   at XCode.DataAccessLayer.DbSession.<>c__DisplayClass34_0`1.<Execute>b__1(DbConnection conn)
   at XCode.DataAccessLayer.DbSession.Process[TResult](Func`2 callback)
   at XCode.DataAccessLayer.DbSession.Execute[T](DbCommand cmd, Boolean query, Func`2 callback)
   at XCode.DataAccessLayer.DbSession.Query(String sql, IDataParameter[] ps)
   at XCode.DataAccessLayer.DAL.Invoke[T1,T2,T3,TResult](IDbSession session, T1 k1, T2 k2, T3 k3, Func`5 callback, String action)
   at XCode.DataAccessLayer.DAL.QueryWrap[T1,T2,T3,TResult](T1 k1, T2 k2, T3 k3, Func`5 callback, String action)
   at XCode.DataAccessLayer.DAL.Query(SelectBuilder builder, Int64 startRowIndex, Int64 maximumRows)
   at XCode.Entity`1.FindAll(Expression where, String order, String selects, Int64 startRowIndex, Int64 maximumRows)
   at XCode.Entity`1.FindAll(Expression where, PageParameter page, String selects)
   at Stardust.Data.Nodes.NodeData.Search(Int32 nodeId, DateTime start, DateTime end, String key, PageParameter page) in D:\Stardust-0812\Stardust.Data\Nodes\节点数据.Biz.cs:line 126
   at Stardust.Web.Areas.Nodes.Controllers.NodeDataController.Search(Pager p) in D:\tardust-0812\Stardust.Web\Areas\Nodes\Controllers\NodeDataController.cs:line 55
   at NewLife.Cube.ReadOnlyEntityController`1.SearchData(Pager p)
   at NewLife.Cube.ReadOnlyEntityController`1.IndexView(Pager p)
   at NewLife.Cube.ReadOnlyEntityController`1.Index(Pager p)
   at lambda_method756(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at NewLife.Cube.WebMiddleware.TenantMiddleware.Invoke(HttpContext ctx)
   at NewLife.Cube.WebMiddleware.RunTimeMiddleware.Invoke(HttpContext ctx)
```

**22:15:11.237 48 Y TP 慢SQL[30,533ms] [StardustData] Select * From NodeHistory Where NodeID=5 Order By Id Desc limit 1082380, 20**

**23:10:37.647 37 Y TP 慢SQL[30,500ms] [StardustData] Select * From NodeData Where NodeID=1 Order By Id Desc limit 488160, 1440**

因为经常跑测试，历史数据比较多，目前大约 共1,083,197条 ，在点分页时经常很慢或查询超时异常了，

我也清楚这个并不是星尘本身的问题，在此只是想问下咱线上星尘节点最多记录大约多少，我只是想对比一下，

从日志中可以看到，查询30多秒最终还失败了， 1百万失败勉强可以接受，40多万查询也挂了，

现在严重怀疑使用的这台机器有问题，但出异常时并没有其它任务执行。 

另外这种情况除了能缩小历史保留时间还有其它优化方法没

是不是可以在**XCode**中或在应用查询时加上异常处理，查询出错时内部重试一定次数，不直接把错误抛给前端。

注意到中间件设置中有个超时重试，但日志中并没有见到重试

谢谢开源这么强大的项目！

**Comment by nnhy** [comment]
一百万数据不多，XCode内部有个参数，超过1000万以后，Select Count 查询将会自动转为FastCount，这将极大加速魔方页面打开速度，代价是表数据的总行数不是精确值，有较小误差。
总行数在100万左右时，它会走Select Count(*)精确查询，此时比较慢。


线上系统，NodeHistory/NodeData这些表保存数千万数据是常态，如果数据库较弱，可以修改数据保存天数，减少数据量。

**Comment by DragonFlyEast** [comment]
谢谢！
